export const services = [
    {
        title: "Miễn phí vận chuyển" ,
        tagline: "Hóa đơn trên 200.000đ" ,
        image: "./images/service.png" ,
    },
    {
        title: "Ưu đãi bất ngờ" ,
        tagline: "Giảm đến 25%",
        image: "./images/service-02.png",
    },
    {
        title: "Hỗ trợ 24/7" ,
        tagline: "Bởi các chuyên gia" ,
        image: "./images/service-03.png" ,
    },
    {
        title: "Giá cả hợp lý" ,
        tagline: "Phù hợp cho mọi người",
        image: "./images/service-04.png",
    },
    {
        title: "Thanh toán an toàn",
        tagline: "Bảo mật 100%",
        image: "./images/service-05.png",
    },
];

export const type = [
    {
        id: 1,
        title: 'T-Shirt' ,
        images: '../images/clothing-shop/t-shirt.png',
        quantity: '3' ,
    },
    {
        id: 2,
        title: 'Shirt',
        images: '../images/clothing-shop/shirt.png',
        quantity: '1',
    },
    {
        id: 3,
        title: 'Sweater',
        images: '../images/clothing-shop/sweater.png',
        quantity: '1',
    },
    {
        id: 4,
        title: 'Hoodie',
        images: '../images/clothing-shop/hoodie.png',
        quantity: '1',
    },
];

export const products = [
    {
        id: 1,
        name: "Áo thun nam nữ unisex tay lỡ AR01, áo phông tay lỡ unisex form rộng oversize streetwear CAM CAM",
        type: 1,
        brand: "Cam Cam",
        quantity: 10,
        price: 63000,
        color: ["#ffffff", "#000000", "#dddddd"],
        tag: "Clothing, T-Shirt, Áo thun",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4,
        description: "Áo thun nam nữ unisex tay lỡ LF 84, áo phông tay lỡ unisex form rộng oversize streetwear THÔNG TIN SẢN PHẨM: - Tên sản phẩm: Áo thun tay lỡ form rộng UNISEX- Xuất sứ: Việt Nam - Chất liệu: cotton DÀY MỀM MỊN MÁT không xù lông. Form áo rộng chuẩn TAY LỠ UNISEX cực đẹp. - Size áo: FREESIZE form rộng- Chiều dài áo: 72cm- Chiều rộng áo: 55cm- Chiều dài tay áo: 20cm- Từ 50-65KG (mặc rộng thoải mái) - Từ 66-75KG (mặc rộngNgày này, áo thun tay lỡ Unisex form rộng đang ngày càng trở nên phổ biến và đa dạng với các mẫu thiết kế độc đáo bắt mắt, thậm chí còn bắt kịp nhiều trào lưu xu hướng đặc biệt là phong cách Hàn Quốc. Do đó, việc tìm hiểu tất tần tật về áo thun tay lỡ nam/nữ là cần thiết giúp bạn luôn cập nhật những mẫu thiết kế mới nhất. Điều này sẽ giúp bạn có nhiều sự lựa chọn mới mẻ và đa dạng phong cách thời trang của bạn.",
        main_image: "./images/clothing-shop/1.png",
        other_image: ["./images/clothing-shop/1-1.png", "./images/clothing-shop/1-2.png"],
        sale: 17,
    },
    {
        id: 2,
        name: "Origami Bird Tee",
        type: 1,
        brand: "Hard Mode",
        quantity: 10,
        price: 69000,
        color: ["#ffffff"],
        tag: "Clothing, T-Shirt, Áo thun",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4.5,
        description: "Size và form áo được đo theo chuẩn của người Việt Nam Nên chọn size lớn hơn nếu bạn thích mặc thoải mái Size M: Chiều cao từ 1m50 – 1m65, cân nặng dưới 60kg Size L: Chiều cao từ 1m65 – 1m72, cân nặng dưới 65kg Size XL: Chiều cao từ 1m70 – 1m77, cân nặng dưới 80kg Bảng size nhằm mục đích hướng dẫn và khích thước có tỉ lệ dung size ± 0.5cm Nếu bạn không chắc chắn về số đo của mình, hãy liên hệ chúng mình để được tư vấn kĩ hơn",
        main_image: "./images/clothing-shop/2.png",
        other_image: ["./images/clothing-shop/2-1.png","./images/clothing-shop/2-2.png","./images/clothing-shop/2-3.png"] ,
        sale: 0,
    },
    {
        id: 3,
        name: "Dragon T-Shirt",
        type: 1,
        brand: "Vergency",
        quantity: 12,
        price: 59000,
        color: ["#dddddd", "#ff0000", "#770000"],
        tag: "Clothing, T-Shirt, Áo thun",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4,
        description: "Size và form áo được đo theo chuẩn của người Việt Nam Nên chọn size lớn hơn nếu bạn thích mặc thoải mái Size M: Chiều cao từ 1m50 – 1m65, cân nặng dưới 60kg Size L: Chiều cao từ 1m65 – 1m72, cân nặng dưới 65kg Size XL: Chiều cao từ 1m70 – 1m77, cân nặng dưới 80kg Bảng size nhằm mục đích hướng dẫn và khích thước có tỉ lệ dung size ± 0.5cm Nếu bạn không chắc chắn về số đo của mình, hãy liên hệ chúng mình để được tư vấn kĩ hơn",
        main_image: "./images/clothing-shop/3.png",
        other_image: ["./images/clothing-shop/3-1.png","./images/clothing-shop/3-2.png","./images/clothing-shop/3-3.png"],
        sale: 25,
    },
    {
        id: 4,
        name: "Áo Sơ Mi Unisex SAIGONESE Cuban Shirt",
        type: 2,
        brand: "Saigonese",
        quantity: 7,
        price: 185000,
        color: ["#ffffff","#000000"],
        tag: "Clothing, Shirt, Áo sơ mi, Áo sơ mi ngắn tay",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4.5,
        description: "Áo Sơ Mi Unisex SGES Cuban Shirt Cotton Lạnh Form Rộng Tay Lỡ / Trắng -Chất liệu: Vải Cotton Lạnh cao cấp, dày dặn, mềm mịn, ít nhăn, thấm hút tốt. Giúp người mặc thoáng mát, không gò bó hay hầm bí. Cam kết không ra màu không bai nhãu. - Dáng áo suông vừa, lên form thoải mái nhưng vẫn vừa vặn với người mặc. - Thiết kế, trẻ trung, dễ dàng kết hợp cùng quần Jeans, Kaki hoặc Short. Đi tiệc, du lịch hay dạo phố cùng bạn bè đều phù hợp Bảng size: Áo Sơ Mi Unisex SGES Cuban Shirt Cotton Lạnh Form Rộng Tay Lỡ / Trắng Size M: 1m6-1m65 45-55kg Size L : 1m66-1m72 56-7//                      kg SizeXL : 1m73-1m77 72-85kg",
        main_image: "./images/clothing-shop/4.png",
        other_image: ["./images/clothing-shop/4-1.png"],
        sale: 0,
    },
    {
        id: 5,
        name: "Áo sweater nam nữ in hình Thỏ dễ thương",
        type: 3,
        brand: "Will's Store",
        quantity: 17,
        price: 110000,
        color: ["#dddddd", "#ff6699", "#ffcc33", "#ffcc99","#66ccff"],
        tag: "Clothing, Sweater",
        status: 1,
        size:[ "S","M","L","XL" ],
        rate: 4,
        description: "Áo sweater nam nữ in hình Thỏ dễ thương, chất nỉ dày dặn, hợp làm áo cặp William - DS152 Thích hợp mặc áo cặp, áo nhóm, áo giữ nhiệt mùa lạnh. Họa tiết sinh động, không bao giờ lỗi mốt. Chất liệu vải nỉ bông mềm mịn, ít xù lông giữ ấm tốt. Size M từ 40kg đến 49kg, Size L từ 50kg đến 60kg. Size XL từ 60kg đến 70kg. uất xứ: Việt Nam Shop kiểm soát chất lượng sản phẩm với mức giá hợp lý trong phân khúc nhé! William cam kết đổi trả khi có lỗi từ NSX hoặc khách hàng không hài lòng.",
        main_image: "./images/clothing-shop/6.png",
        other_image: ["./images/clothing-shop/6-1.png","./images/clothing-shop/6-2.png","./images/clothing-shop/6-3.png","./images/clothing-shop/6-4.png"],
        sale: 0,
    },
    {
        id: 6,
        name: "Hoodie Zip Signature",
        type: 4,
        brand: "Outerity",
        quantity: 11,
        price: 320000,
        color: ["#ff6699"],
        tag: "Clothing, Hoodie, Áo khoác",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4,
        description: "Không có",
        main_image: "./images/clothing-shop/7.png",
        other_image: ["./images/clothing-shop/7-1.png","./images/clothing-shop/7-2.png","./images/clothing-shop/7-3.png","./images/clothing-shop/7-4.png"],
        sale: 37,
    },
    {
        id: 7,
        name: "HARDMODE® MOON SHIRT",
        type: 2,
        brand: "Hard Mode",
        quantity: 11,
        price: 119000,
        color: ["#ff6699"],
        tag: "Clothing, Shirt, Áo sơ mi, Áo sơ mi ngắn tay",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4.5,
        description: "Không có",
        main_image: "./images/clothing-shop/8.png",
        other_image: ["./images/clothing-shop/8-1.png","./images/clothing-shop/8-2.png","./images/clothing-shop/8-3.png"],
        sale: 37,
    },
];

export const brands = [
    {
        name: "Outerity",
        image: "./images/clothing-shop/outerity.png",
    },
    {
        name: "Hardmode",
        image: "./images/clothing-shop/hardmode.png",
    },
    {
        name: "Vergency",
        image: "./images/clothing-shop/vergency.png",
    },
    {
        name: "Will",
        image:  "./images/clothing-shop/will.png",
    },
    {
        name: "Saigonese",
        image: "./images/clothing-shop/saigonese.png",
    },
]

export const sizes = [ "S","M","L","XL"];

export const colors = ["#dddddd", "#ff6699", "#ffcc33", "#ffcc99","#66ccff","#ff6699","#ffffff", "#000000","#ff0000", "#770000"];


export const tags = ["Clothing", "Áo thun", "Áo", "Áo sơ mi", "Áo sơ mi tay ngắn", "Áo khoác", "Sweater", "Hoodie"];


export const compare = [
    {
        id: 4,
        name: "Áo Sơ Mi Unisex SAIGONESE Cuban Shirt",
        type: 2,
        brand: "Saigonese",
        quantity: 7,
        price: 185000,
        color: ["#ffffff","#000000"],
        tag: "Clothing, Shirt, Áo sơ mi, Áo sơ mi ngắn tay",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4.5,
        description: "Áo Sơ Mi Unisex SGES Cuban Shirt Cotton Lạnh Form Rộng Tay Lỡ / Trắng -Chất liệu: Vải Cotton Lạnh cao cấp, dày dặn, mềm mịn, ít nhăn, thấm hút tốt. Giúp người mặc thoáng mát, không gò bó hay hầm bí. Cam kết không ra màu không bai nhãu. - Dáng áo suông vừa, lên form thoải mái nhưng vẫn vừa vặn với người mặc. - Thiết kế, trẻ trung, dễ dàng kết hợp cùng quần Jeans, Kaki hoặc Short. Đi tiệc, du lịch hay dạo phố cùng bạn bè đều phù hợp Bảng size: Áo Sơ Mi Unisex SGES Cuban Shirt Cotton Lạnh Form Rộng Tay Lỡ / Trắng Size M: 1m6-1m65 45-55kg Size L : 1m66-1m72 56-7//                      kg SizeXL : 1m73-1m77 72-85kg",
        main_image: "./images/clothing-shop/4.png",
        other_image: ["./images/clothing-shop/4-1.png"],
        sale: 0,
    },
    {
        id: 5,
        name: "Áo sweater nam nữ in hình Thỏ dễ thương",
        type: 3,
        brand: "Will's Store",
        quantity: 17,
        price: 110000,
        color: ["#dddddd", "#ff6699", "#ffcc33", "#ffcc99","#66ccff"],
        tag: "Clothing, Sweater",
        status: 1,
        size:[ "S","M","L","XL" ],
        rate: 4,
        description: "Áo sweater nam nữ in hình Thỏ dễ thương, chất nỉ dày dặn, hợp làm áo cặp William - DS152 Thích hợp mặc áo cặp, áo nhóm, áo giữ nhiệt mùa lạnh. Họa tiết sinh động, không bao giờ lỗi mốt. Chất liệu vải nỉ bông mềm mịn, ít xù lông giữ ấm tốt. Size M từ 40kg đến 49kg, Size L từ 50kg đến 60kg. Size XL từ 60kg đến 70kg. uất xứ: Việt Nam Shop kiểm soát chất lượng sản phẩm với mức giá hợp lý trong phân khúc nhé! William cam kết đổi trả khi có lỗi từ NSX hoặc khách hàng không hài lòng.",
        main_image: "./images/clothing-shop/6.png",
        other_image: ["./images/clothing-shop/6-1.png","./images/clothing-shop/6-2.png","./images/clothing-shop/6-3.png","./images/clothing-shop/6-4.png"],
        sale: 0,
    },
]

export const wishlist = [
    {
        id: 6,
        name: "Hoodie Zip Signature",
        type: 4,
        brand: "Outerity",
        quantity: 11,
        price: 320000,
        color: ["#ff6699"],
        tag: "Clothing, Hoodie, Áo khoác",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4,
        description: "Không có",
        main_image: "./images/clothing-shop/7.png",
        other_image: ["./images/clothing-shop/7-1.png","./images/clothing-shop/7-2.png","./images/clothing-shop/7-3.png","./images/clothing-shop/7-4.png"],
        sale: 37,
    },
]

export const cart = [
    {
        id: 1,
        name: "Áo thun nam nữ unisex tay lỡ AR01, áo phông tay lỡ unisex form rộng oversize streetwear CAM CAM",
        type: 1,
        brand: "Cam Cam",
        quantity: 10,
        price: 63000,
        color: ["#ffffff", "#000000", "#dddddd"],
        tag: "Clothing, T-Shirt, Áo thun",
        status: 1,
        size: [ "S","M","L","XL" ],
        rate: 4,
        description: "Áo thun nam nữ unisex tay lỡ LF 84, áo phông tay lỡ unisex form rộng oversize streetwear THÔNG TIN SẢN PHẨM: - Tên sản phẩm: Áo thun tay lỡ form rộng UNISEX- Xuất sứ: Việt Nam - Chất liệu: cotton DÀY MỀM MỊN MÁT không xù lông. Form áo rộng chuẩn TAY LỠ UNISEX cực đẹp. - Size áo: FREESIZE form rộng- Chiều dài áo: 72cm- Chiều rộng áo: 55cm- Chiều dài tay áo: 20cm- Từ 50-65KG (mặc rộng thoải mái) - Từ 66-75KG (mặc rộngNgày này, áo thun tay lỡ Unisex form rộng đang ngày càng trở nên phổ biến và đa dạng với các mẫu thiết kế độc đáo bắt mắt, thậm chí còn bắt kịp nhiều trào lưu xu hướng đặc biệt là phong cách Hàn Quốc. Do đó, việc tìm hiểu tất tần tật về áo thun tay lỡ nam/nữ là cần thiết giúp bạn luôn cập nhật những mẫu thiết kế mới nhất. Điều này sẽ giúp bạn có nhiều sự lựa chọn mới mẻ và đa dạng phong cách thời trang của bạn.",
        main_image: "./images/clothing-shop/1.png",
        other_image: ["./images/clothing-shop/1-1.png", "./images/clothing-shop/1-2.png"],
        sale: 17,
    },
]